// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_System.Context;

#nullable disable

namespace University_System.Migrations
{
    [DbContext(typeof(UniContext))]
    [Migration("20260415234909_initialmigration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University_System.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Maple Street, New York, NY 10001",
                            Email = "alice.johnson@university.edu",
                            Image = "https://randomuser.me/api/portraits/women/44.jpg",
                            Name = "Alice Johnson",
                            Phone = "+1 (555) 101-2020",
                            SSN = "123-45-6789"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Oak Avenue, Los Angeles, CA 90001",
                            Email = "bob.martinez@university.edu",
                            Image = "https://randomuser.me/api/portraits/men/32.jpg",
                            Name = "Bob Martinez",
                            Phone = "+1 (555) 303-4040",
                            SSN = "987-65-4321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 Pine Road, Chicago, IL 60601",
                            Email = "clara.smith@university.edu",
                            Image = "https://randomuser.me/api/portraits/women/68.jpg",
                            Name = "Clara Smith",
                            Phone = "+1 (555) 505-6060",
                            SSN = "456-78-9012"
                        },
                        new
                        {
                            Id = 4,
                            Address = "99 Birch Blvd, Houston, TX 77001",
                            Email = "david.lee@university.edu",
                            Image = "https://randomuser.me/api/portraits/men/75.jpg",
                            Name = "David Lee",
                            Phone = "+1 (555) 707-8080",
                            SSN = "321-54-8765"
                        },
                        new
                        {
                            Id = 5,
                            Address = "33 Cedar Lane, Phoenix, AZ 85001",
                            Email = "emma.wilson@university.edu",
                            Image = "https://randomuser.me/api/portraits/women/12.jpg",
                            Name = "Emma Wilson",
                            Phone = "+1 (555) 909-1010",
                            SSN = "654-32-1987"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
